### PR TITLE
Add pre-commit hooks and a 'make test' target

### PR DESCRIPTION
**Pull request by jvperrin**
This should do some testing during the service build at least, and I could see more hooks being added later for things like validating HTML, etc.

### CODE REVIEW

**Review by ja5087 — APPROVED** [review]
lgtm, thanks!

**Comment by jvperrin** [comment]
Looks like this broke due to differing python versions (I was testing locally with 3.7 but the jenkins pipeline was using the system default of 3.5). I'll take a look at that and try and fix it.

**Comment by jvperrin** [comment]
I thought I had fixed this with 1cce7165a0d476d32660f6b2628b2e10b4e94003, but it seems like the `make test` and `make cook-image` jobs are both trying to create the virtualenv in the same directory at the same time (and they run in parallel), so there's some issues with that.

**Comment by jvperrin** [comment]
Alright, with b5c56cfc32932264aa244f3b185d4ea1d40e5609 and 87a1e1731f2db0cd62de96a98ce2683b25756af6 this is finally fixed. `flock` to the rescue!

**Pull request merged**
